# Generated by Django 4.1.5 on 2023-01-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BT', 'BTech'), ('MT', 'MTech'), ('PH', 'PhD')], default='BT', max_length=2),
        ),
    ]
