# Generated by Django 4.1.5 on 2023-01-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_student_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Accepted')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='openings',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('CSD', 'CSD'), ('CSB', 'CSB'), ('CSSS', 'CSSS'), ('CSAI', 'CSAI'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CB', 'CB')], default='CSE', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('B', 'BTech'), ('M', 'MTech'), ('P', 'PhD')], default='B', max_length=1),
        ),
    ]
